.PHONY: zsh vim tmux regolith ssh scripts git alacritty

all: zsh vim tmux regolith ssh scripts


server: zsh vim tmux
vm: tools zsh vim tmux
desktop: zsh vim tmux regolith ssh git

tools:
	sudo apt install tmux curl git python3-pip
	sudo pip install pynvim

zsh:
	cp ./zsh/aliases ~/.aliases
	cp ./zsh/profile ~/.profile
	cp ./zsh/zshrc ~/.zshrc
	mkdir -p ~/.config/zsh/antigen
	@git clone https://github.com/zsh-users/antigen.git ~/.config/zsh/antigen | true
	git -C ~/.config/zsh/antigen pull

vim:
	mkdir -p ~/bin
	@ln -s `which nvim` ~/bin | true
	curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	make -C ./vim/ install

tmux:
	@git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm | true
	git -C ~/.tmux/plugins/tpm pull
	cp ./tmux/tmux.conf ~/.tmux.conf

regolith:
	cp -r ./regolith3 ~/.config/

ssh:
	cp ./ssh/config ~/.ssh/config
	touch ~/.ssh/hosts
	./scripts/hosts > ~/.ssh/autogenerated-hosts

scripts:
	mkdir -p ~/bin
	cp ./scripts/* ~/bin

git:
	cp ./git/gitconfig ~/.gitconfig
	cp ./git/gitmessage ~/.gitmessage

fish:
	mkdir -p ~/.config/fish/functions
	cp fishsh/config.fish ~/.config/fish/config.fish
	cp fishsh/functions/* ~/.config/fish/functions

alacritty:
	mkdir -p ~/.config/alacritty/
	cp alacritty/alacritty.toml ~/.config/alacritty/alacritty.toml
