set nocompatible
filetype off

source ~/.config/nvim/plugins.vim
source ~/.config/nvim/general.vim
source ~/.config/nvim/theme.vim
source ~/.config/nvim/keybinding.vim
source ~/.config/nvim/ui.vim
source ~/.config/nvim/lang.vim
source ~/.config/nvim/latex.vim
