#!/bin/sh
if command -v apt ; then
    sudo apt update
    sudo apt upgrade
    sudo apt autoremove
fi 
if command -v snap ; then
    sudo snap refresh
fi
if command -v flatpak ; then
    sudo flatpak update
    # Prune unused runtimes
    sudo flatpak uninstall --unused
fi
