#!/bin/sh
if command -v apt ; then
    sudo apt update
    sudo apt -y upgrade
    sudo apt -y autoremove
fi 
if command -v snap ; then
    sudo snap refresh
fi
if command -v flatpak ; then
    sudo flatpak update -y
    # Prune unused runtimes
    sudo flatpak uninstall -y --unused
fi
# if command -v docker ; then
#    sudo docker images --format "{{.Repository}}:{{.Tag}}" \
#        | grep --invert-match '<none>' \
#        | xargs -r -L1 docker pull
# fi
