#!/bin/sh
if command -v apt ; then
    sudo apt update
    sudo apt upgrade
    sudo apt autoremove
fi 
if command -v snap ; then
    sudo snap refresh
fi
if command -v flatpak ; then
    sudo flatpak update
    # Prune unused runtimes
    sudo flatpak uninstall --unused
fi
if command -v docker ; then
    docker images --format "{{.Repository}}:{{.Tag}}" | grep --invert-match '<none>' | xargs -L1 docker pull
fi
