set -g default-shell $SHELL

# True colors

set-option -sa terminal-overrides ',xterm-256color:Tc'

set -g @nova-segment-mode "#{?client_prefix,Ω,ω}"
set -g @nova-pane-active-border-style "#44475a"
set -g @nova-pane-border-style "#282a36"
set -g @nova-status-style-bg "#e0e0e0"
set -g @nova-status-style-fg "#101010"
set -g @nova-status-style-active-bg "#89c0d0"
set -g @nova-status-style-active-fg "#2e3540"
set -g @nova-status-style-double-bg "#2d3540"


set -g @nova-pane "#I#{?pane_in_mode, #{pane_mode},} #W"

set -g @nova-segment-hostinfo "#h | %a %Y-%m-%d %H:%M"
set -g @nova-segment-hostinfo-colors "#e0e0e0 #101010"

set -g @nova-rows 0
set -g @nova-segments-0-left "mode"
set -g @nova-segments-0-right "hostinfo"


# pane stuff
set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1


# Mouse Control
set -g mouse on

# Get a better prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Split panes better
bind c new-window      -c "#{pane_current_path}"
bind [ split-window -h -c "#{pane_current_path}"
bind ] split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind < previous-window
bind > next-window

# Navigate better

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D


# Plugins

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'o0th/tmux-nova'

run '~/.tmux/plugins/tpm/tpm'

# theme

# useful

set -g allow-passthrough on
set -g set-clipboard on
set -g @yank_with_mouse on
set -g @yank_action 'copy-pipe-no-clear'
